project:
  type: website

execute:
  freeze: auto

website:
  page-navigation: true
  title: "Generative AI for Business Applications"
  description: "Website for GenAI project at HdM Stuttgart, SS 2025, Prof. Dr. Jan Kirenz."
  # site-url: "https://llms-ws2324.github.io//website/"
  # repo-url: https://github.com/llms-ws2324/website
  # repo-actions: [edit, issue]
  # open-graph: true
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search:
    type: overlay  
  page-footer:
    left: |
      © [Jan Kirenz](https://www.kirenz.com/), 2025
    center:
      - text: "Schedule"
        href: index.qmd
      - text: "Syllabus"
        href: course-syllabus.qmd  
    right:
      - icon: person-circle
      - text: "Moodle"
        href: https://moodle.hdm-stuttgart.de/course/view.php?id=21923
        aria-label: Moodle    
#    background: "#325b74"    


  sidebar:
#    background: "#325b74"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/orgs/generative-ai-ss25/repositories
        text: "GitHub organization"
      - icon: person-fill
        text: "Moodle"
        href: https://moodle.hdm-stuttgart.de/course/view.php?id=21923

    style: docked
    search: true
    collapse-level: 2
    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
            text: Schedule        
          - href: weeks.qmd
            text: Weekly Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support

      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources


format:
  html:
    toc: false
    theme: cosmo
    css: custom.scss
    code-copy: true
    highlight-style: github-dark
    code-overflow: wrap
    author-meta: "Jan Kirenz"
    callout-appearance: simple
    include-in-header:
      - text: |
          <script src="password.js"></script>